In [94]:
import pandas as pd
import operator
import functools

In [66]:
search = pd.read_excel("Edited.xlsx", sheet_name=1)
search.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45
0,NaN,NaN,C10YUSAX=R,JPM10YUSAX=R,GS10YUSAX=R,BAC10YUSAX=R,MS10YUSAX=R,WFC10YUSAX=R,RY10YUSAX=R,BMO10YUSAX=R,...,PNC10YUSAR=R,PNCB10YUSAR=R,MS10YUSSR=R,WFC10YUSSC=R,TD10YUSAX=R,GS10YUSSX=MG,MS10YUSSX=MG,WFC10YUSSX=MG,BAC10YUSSX=MG,C10YUSSX=MG
1,Дата,День недели,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-05-01 00:00:00,2010-05-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-05-02 00:00:00,2010-05-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010-05-03 00:00:00,2010-05-03 00:00:00,-94.9,-50.2,0,-53.7,-46.6,-43.9,NaN,NaN,...,NaN,NaN,-247.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
firms = pd.read_csv("firm - firm.csv", sep=";", names=["company", "date", "price"])
firms.head()

  company        date      price
0     AFL  10.05.2010  18.938135
1     AFL  11.05.2010  18.629795
2     AFL  12.05.2010  19.048532
3     AFL  13.05.2010  18.431849
4     AFL  14.05.2010  17.472565

In [186]:
request = pd.read_csv("request - request.csv", header=None, names=["event", "company", "market", "date", "type", "l", "r", "w", "c"])
request.to_csv("request - request;.csv", sep=";", header=False, index=False)
request.head()
request.assign(l=-1, r=1, w=-2, c=4).to_csv("request - request.1;.csv", sep=";", header=False, index=False)
request.assign(l=-5, r=5, w=-10, c=12).to_csv("request - request.2;.csv", sep=";", header=False, index=False)
request.assign(l=-30, r=30, w=-60, c=62).to_csv("request - request.3;.csv", sep=";", header=False, index=False)

In [73]:
r_tickers = set(request.iloc[:, 1].unique())

In [26]:
header = ["date", "week", *search.iloc[0, 2:]]

In [34]:
search1 = pd.DataFrame(search.iloc[2:].values, columns=header).drop("week", axis=1)

In [157]:
search_melt = (
    pd.melt(search1, id_vars="date", var_name="company", value_name="price")
    [["company", "date", "price"]]
    .assign(company= lambda df: df.company.str.split("10").apply(operator.itemgetter(0)))
    .query("date==date")
    .drop_duplicates(["date", "company"])
)
search_melt = search_melt[search_melt.company.isin(r_tickers)]

In [165]:
search_melt

      company       date price
3899      JPM 2010-05-01   NaN
3900      JPM 2010-05-02   NaN
3901      JPM 2010-05-03 -50.2
3902      JPM 2010-05-04 -48.1
3903      JPM 2010-05-05 -37.6
3904      JPM 2010-05-06   -44
3905      JPM 2010-05-07 -31.9
3906      JPM 2010-05-08   NaN
3907      JPM 2010-05-09   NaN
3908      JPM 2010-05-10 -31.1
3909      JPM 2010-05-11 -53.8
3910      JPM 2010-05-12 -47.4
3911      JPM 2010-05-13 -53.3
3912      JPM 2010-05-14 -51.2
3913      JPM 2010-05-15   NaN
3914      JPM 2010-05-16   NaN
3915      JPM 2010-05-17 -66.5
3916      JPM 2010-05-18 -65.8
3917      JPM 2010-05-19   -63
3918      JPM 2010-05-20 -62.2
3919      JPM 2010-05-21 -73.9
3920      JPM 2010-05-22   NaN
3921      JPM 2010-05-23   NaN
3922      JPM 2010-05-24 -77.4
3923      JPM 2010-05-25 -65.6
3924      JPM 2010-05-26 -59.7
3925      JPM 2010-05-27 -68.5
3926      JPM 2010-05-28 -63.3
3927      JPM 2010-05-29   NaN
3928      JPM 2010-05-30   NaN
...       ...        ...   ...
77949     PNC 2020-12-02   NaN
77950     PNC 2020-12-03   NaN
77951     PNC 2020-12-04   NaN
77952     PNC 2020-12-05   NaN
77953     PNC 2020-12-06   NaN
77954     PNC 2020-12-07   NaN
77955     PNC 2020-12-08   NaN
77956     PNC 2020-12-09   NaN
77957     PNC 2020-12-10   NaN
77958     PNC 2020-12-11   NaN
77959     PNC 2020-12-12   NaN
77960     PNC 2020-12-13   NaN
77961     PNC 2020-12-14   NaN
77962     PNC 2020-12-15   NaN
77963     PNC 2020-12-16   NaN
77964     PNC 2020-12-17   NaN
77965     PNC 2020-12-18   NaN
77966     PNC 2020-12-19   NaN
77967     PNC 2020-12-20   NaN
77968     PNC 2020-12-21   NaN
77969     PNC 2020-12-22   NaN
77970     PNC 2020-12-23   NaN
77971     PNC 2020-12-24   NaN
77972     PNC 2020-12-25   NaN
77973     PNC 2020-12-26   NaN
77974     PNC 2020-12-27   NaN
77975     PNC 2020-12-28   NaN
77976     PNC 2020-12-29   NaN
77977     PNC 2020-12-30   NaN
77978     PNC 2020-12-31   NaN

[23388 rows x 3 columns]

In [61]:
request

,1,AFL,NYK,24.05.2016,fraud,-2,2,-4,6,insurance,Unnamed: 10,Event ID,Unnamed: 12,Unnamed: 13,Unnamed: 14,AFL.1
0,3,AFL,NYK,30.10.2013,fraud,-2,2,-4,6,insurance,NaN,1.0,insurance,NaN,NaN,ANAT
1,6,AFL,NYK,29.11.2012,fraud,-2,2,-4,6,insurance,NaN,3.0,insurance,NaN,NaN,AON
2,12,ANAT,NYK,22.03.2021,fraud,-2,2,-4,6,insurance,NaN,6.0,insurance,NaN,NaN,ARCC
3,20,AON,NYK,14.04.2021,fraud,-2,2,-4,6,insurance,NaN,12.0,insurance,NaN,NaN,AXP
4,21,AON,NYK,06.03.2019,fraud,-2,2,-4,6,insurance,NaN,20.0,insurance,NaN,NaN,BAC
5,23,AON,NYK,20.07.2020,fraud,-2,2,-4,6,insurance,NaN,21.0,insurance,NaN,NaN,BHF
6,26,AON,NYK,13.04.2021,fraud,-2,2,-4,6,insurance,NaN,23.0,insurance,NaN,NaN,BK
7,30,ARCC,NYK,14.04.2021,fraud,-2,2,-4,6,asset management,NaN,26.0,insurance,NaN,NaN,BLK
8,36,ARCC,NYK,17.11.2020,fraud,-2,2,-4,6,asset management,NaN,30.0,asset management,NaN,NaN,BRK-A
9,37,ARCC,NYK,01.02.2017,fraud,-2,2,-4,6,asset management,NaN,36.0,asset management,NaN,NaN,CG
10,38,ARCC,NYK,20.02.2018,fraud,-2,2,-4,6,asset management,NaN,37.0,asset management,NaN,NaN,CINF
11,42,AXP,NYK,22.03.2021,fraud,-2,2,-4,6,banking,NaN,38.0,asset management,NaN,NaN,CME
12,50,BAC,NYK,07.10.2020,fraud,-2,2,-4,6,banking,NaN,42.0,banking,NaN,NaN,CNO
13,51,BAC,NYK,27.02.2018,fraud,-2,2,-4,6,banking,NaN,50.0,banking,NaN,NaN,DFS
14,54,BAC,NYK,15.07.2015,fraud,-2,2,-4,6,banking,NaN,51.0,banking,NaN,NaN,FAF
15,55,BAC,NYK,31.01.2013,fraud,-2,2,-4,6,banking,NaN,54.0,banking,NaN,NaN,FCNCA
16,56,BAC,NYK,08.10.2009,fraud,-2,2,-4,6,banking,NaN,55.0,banking,NaN,NaN,FITB
17,57,BAC,NYK,07.12.2018,fraud,-2,2,-4,6,banking,NaN,57.0,banking,NaN,NaN,FMBI
18,58,BAC,NYK,20.02.2018,fraud,-2,2,-4,6,banking,NaN,58.0,banking,NaN,NaN,FNF
19,60,BHF,NYK,13.04.2021,fraud,-2,2,-4,6,insurance,NaN,60.0,insurance,NaN,NaN,GL
20,64,BHF,NYK,22.03.2021,fraud,-2,2,-4,6,insurance,NaN,64.0,insurance,NaN,NaN,HMN
21,65,BHF,NYK,09.04.2021,fraud,-2,2,-4,6,insurance,NaN,65.0,insurance,NaN,NaN,HWC
22,67,BHF,NYK,01.02.2017,fraud,-2,2,-4,6,insurance,NaN,70.0,banking,NaN,NaN,ISBC
23,70,BK,NYK,07.10.2020,fraud,-2,2,-4,6,banking,NaN,71.0,banking,NaN,NaN,IVZ
24,71,BK,NYK,27.02.2018,fraud,-2,2,-4,6,banking,NaN,74.0,banking,NaN,NaN,JEF
25,74,BK,NYK,15.07.2015,fraud,-2,2,-4,6,banking,NaN,75.0,banking,NaN,NaN,JPM
26,75,BK,NYK,31.01.2013,fraud,-2,2,-4,6,banking,NaN,77.0,banking,NaN,NaN,MMC
27,76,BK,NYK,08.10.2009,fraud,-2,2,-4,6,banking,NaN,78.0,banking,NaN,NaN,NDAQ
28,77,BK,NYK,07.12.2018,fraud,-2,2,-4,6,banking,NaN,81.0,asset management,NaN,NaN,PGR
29,78,BK,NYK,20.02.2018,fraud,-2,2,-4,6,banking,NaN,82.0,asset management,NaN,NaN,PNC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,398,SIGI,NYK,22.03.2021,fraud,-2,2,-4,6,insurance,NaN,405.0,banking,NaN,NaN,NaN
134,400,SIVB,NYK,14.04.2021,fraud,-2,2,-4,6,banking,NaN,406.0,banking,NaN,NaN,NaN
135,403,SIVB,NYK,01.12.2019,fraud,-2,2,-4,6,banking,NaN,407.0,banking,NaN,NaN,NaN
136,405,SIVB,NYK,12.04.2021,fraud,-2,2,-4,6,banking,NaN,413.0,insurance,NaN,NaN,NaN
137,406,SIVB,NYK,14.04.2021,fraud,-2,2,-4,6,banking,NaN,415.0,insurance,NaN,NaN,NaN
138,407,SIVB,NYK,13.04.2021,fraud,-2,2,-4,6,banking,NaN,416.0,insurance,NaN,NaN,NaN
139,413,THG,NYK,14.04.2021,fraud,-2,2,-4,6,insurance,NaN,420.0,banking,NaN,NaN,NaN
140,415,THG,NYK,12.04.2021,fraud,-2,2,-4,6,insurance,NaN,425.0,banking,NaN,NaN,NaN
141,416,THG,NYK,13.04.2021,fraud,-2,2,-4,6,insurance,NaN,428.0,banking,NaN,NaN,NaN
142,420,UMPQ,NYK,14.04.2021,fraud,-2,2,-4,6,banking,NaN,429.0,banking,NaN,NaN,NaN
143,425,UMPQ,NYK,13.04.2021,fraud,-2,2,-4,6,banking,NaN,431.0,insurance,NaN,NaN,NaN
144,428,UMPQ,NYK,14.04.2021,fraud,-2,2,-4,6,banking,NaN,432.0,insurance,NaN,NaN,NaN
145,429,UMPQ,NYK,21.07.2015,fraud,-2,2,-4,6,banking,NaN,435.0,insurance,NaN,NaN,NaN
146,431,UNM,NYK,14.04.2021,fraud,-2,2,-4,6,insurance,NaN,440.0,banking,NaN,NaN,NaN
147,432,UNM,NYK,14.04.2021,fraud,-2,2,-4,6,insurance,NaN,444.0,banking,NaN,NaN,NaN
148,435,UNM,NYK,13.04.2021,fraud,-2,2,-4,6,insurance,NaN,446.0,banking,NaN,NaN,NaN
149,440,USB,NYK,07.04.2021,fraud,-2,2,-4,6,banking,NaN,448.0,banking,NaN,NaN,NaN
150,444,USB,NYK,09.04.2021,fraud,-2,2,-4,6,banking,NaN,463.0,banking,NaN,NaN,NaN
151,446,USB,NYK,22.03.2021,fraud,-2,2,-4,6,banking,NaN,465.0,banking,NaN,NaN,NaN
152,448,USB,NYK,04.03.2021,fraud,-2,2,-4,6,banking,NaN,471.0,insurance,NaN,NaN,NaN
153,463,WFC,NYK,13.04.2021,fraud,-2,2,-4,6,banking,NaN,473.0,insurance,NaN,NaN,NaN
154,465,WFC,NYK,22.03.2021,fraud,-2,2,-4,6,banking,NaN,477.0,insurance,NaN,NaN,NaN
155,471,WRB,NYK,12.04.2021,fraud,-2,2,-4,6,insurance,NaN,481.0,banking,NaN,NaN,NaN
156,473,WRB,NYK,13.04.2021,fraud,-2,2,-4,6,insurance,NaN,482.0,banking,NaN,NaN,NaN
157,477,WRB,NYK,04.02.2019,fraud,-2,2,-4,6,insurance,NaN,484.0,banking,NaN,NaN,NaN
158,481,ZION,NYK,14.04.2021,fraud,-2,2,-4,6,banking,NaN,486.0,banking,NaN,NaN,NaN
159,482,ZION,NYK,14.04.2021,fraud,-2,2,-4,6,banking,NaN,487.0,banking,NaN,NaN,NaN
160,484,ZION,NYK,12.04.2021,fraud,-2,2,-4,6,banking,NaN,NaN,NaN,NaN,NaN,NaN
161,486,ZION,NYK,14.04.2021,fraud,-2,2,-4,6,banking,NaN,NaN,NaN,NaN,NaN,NaN
162,487,ZION,NYK,13.04.2021,fraud,-2,2,-4,6,banking,NaN,NaN,NaN,NaN,NaN,NaN

In [168]:
search_melt.dropna().to_csv("search_request.csv", sep=";", index=False, header=False, date_format="%d.%m.%Y")