In [1]:
import pandas as pd

In [49]:
request = pd.read_csv(
    "request - request.csv", header=None, 
    converters={3: lambda x:pd.to_datetime(x, format="%d.%m.%Y")}, usecols=range(10),
    names=["event", "company", "market", "date", "type", "l", "r", "w", "c", "sector"]
)

In [63]:
pd.tseries.offsets.QuarterEnd()

In [80]:
(5-1) // 3 + 1

2

In [81]:
request1 = (
    request
    .query("date >= '2010-05-01'")
    .assign(quarter=lambda df: df.date.apply(lambda d: pd.datetime(d.year, (d.month-1) // 3 * 3 + 1, 1)))
)

In [82]:
request1

,event,company,market,date,type,l,r,w,c,sector,quarter
0,1,AFL,NYK,2016-05-24,fraud,-2,2,-4,6,insurance,2016-04-01
1,3,AFL,NYK,2013-10-30,fraud,-2,2,-4,6,insurance,2013-10-01
2,6,AFL,NYK,2012-11-29,fraud,-2,2,-4,6,insurance,2012-10-01
3,12,ANAT,NYK,2021-03-22,fraud,-2,2,-4,6,insurance,2021-01-01
4,20,AON,NYK,2021-04-14,fraud,-2,2,-4,6,insurance,2021-04-01
5,21,AON,NYK,2019-03-06,fraud,-2,2,-4,6,insurance,2019-01-01
6,23,AON,NYK,2020-07-20,fraud,-2,2,-4,6,insurance,2020-07-01
7,26,AON,NYK,2021-04-13,fraud,-2,2,-4,6,insurance,2021-04-01
8,30,ARCC,NYK,2021-04-14,fraud,-2,2,-4,6,asset management,2021-04-01
9,36,ARCC,NYK,2020-11-17,fraud,-2,2,-4,6,asset management,2020-10-01
10,37,ARCC,NYK,2017-02-01,fraud,-2,2,-4,6,asset management,2017-01-01
11,38,ARCC,NYK,2018-02-20,fraud,-2,2,-4,6,asset management,2018-01-01
12,42,AXP,NYK,2021-03-22,fraud,-2,2,-4,6,banking,2021-01-01
13,50,BAC,NYK,2020-10-07,fraud,-2,2,-4,6,banking,2020-10-01
14,51,BAC,NYK,2018-02-27,fraud,-2,2,-4,6,banking,2018-01-01
15,54,BAC,NYK,2015-07-15,fraud,-2,2,-4,6,banking,2015-07-01
16,55,BAC,NYK,2013-01-31,fraud,-2,2,-4,6,banking,2013-01-01
18,57,BAC,NYK,2018-12-07,fraud,-2,2,-4,6,banking,2018-10-01
19,58,BAC,NYK,2018-02-20,fraud,-2,2,-4,6,banking,2018-01-01
20,60,BHF,NYK,2021-04-13,fraud,-2,2,-4,6,insurance,2021-04-01
21,64,BHF,NYK,2021-03-22,fraud,-2,2,-4,6,insurance,2021-01-01
22,65,BHF,NYK,2021-04-09,fraud,-2,2,-4,6,insurance,2021-04-01
23,67,BHF,NYK,2017-02-01,fraud,-2,2,-4,6,insurance,2017-01-01
24,70,BK,NYK,2020-10-07,fraud,-2,2,-4,6,banking,2020-10-01
25,71,BK,NYK,2018-02-27,fraud,-2,2,-4,6,banking,2018-01-01
26,74,BK,NYK,2015-07-15,fraud,-2,2,-4,6,banking,2015-07-01
27,75,BK,NYK,2013-01-31,fraud,-2,2,-4,6,banking,2013-01-01
29,77,BK,NYK,2018-12-07,fraud,-2,2,-4,6,banking,2018-10-01
30,78,BK,NYK,2018-02-20,fraud,-2,2,-4,6,banking,2018-01-01
31,81,BLK,NYK,2011-07-28,fraud,-2,2,-4,6,asset management,2011-07-01
...,...,...,...,...,...,...,...,...,...,...,...
134,398,SIGI,NYK,2021-03-22,fraud,-2,2,-4,6,insurance,2021-01-01
135,400,SIVB,NYK,2021-04-14,fraud,-2,2,-4,6,banking,2021-04-01
136,403,SIVB,NYK,2019-12-01,fraud,-2,2,-4,6,banking,2019-10-01
137,405,SIVB,NYK,2021-04-12,fraud,-2,2,-4,6,banking,2021-04-01
138,406,SIVB,NYK,2021-04-14,fraud,-2,2,-4,6,banking,2021-04-01
139,407,SIVB,NYK,2021-04-13,fraud,-2,2,-4,6,banking,2021-04-01
140,413,THG,NYK,2021-04-14,fraud,-2,2,-4,6,insurance,2021-04-01
141,415,THG,NYK,2021-04-12,fraud,-2,2,-4,6,insurance,2021-04-01
142,416,THG,NYK,2021-04-13,fraud,-2,2,-4,6,insurance,2021-04-01
143,420,UMPQ,NYK,2021-04-14,fraud,-2,2,-4,6,banking,2021-04-01
144,425,UMPQ,NYK,2021-04-13,fraud,-2,2,-4,6,banking,2021-04-01
145,428,UMPQ,NYK,2021-04-14,fraud,-2,2,-4,6,banking,2021-04-01
146,429,UMPQ,NYK,2015-07-21,fraud,-2,2,-4,6,banking,2015-07-01
147,431,UNM,NYK,2021-04-14,fraud,-2,2,-4,6,insurance,2021-04-01
148,432,UNM,NYK,2021-04-14,fraud,-2,2,-4,6,insurance,2021-04-01
149,435,UNM,NYK,2021-04-13,fraud,-2,2,-4,6,insurance,2021-04-01
150,440,USB,NYK,2021-04-07,fraud,-2,2,-4,6,banking,2021-04-01
151,444,USB,NYK,2021-04-09,fraud,-2,2,-4,6,banking,2021-04-01
152,446,USB,NYK,2021-03-22,fraud,-2,2,-4,6,banking,2021-01-01
153,448,USB,NYK,2021-03-04,fraud,-2,2,-4,6,banking,2021-01-01
154,463,WFC,NYK,2021-04-13,fraud,-2,2,-4,6,banking,2021-04-01
155,465,WFC,NYK,2021-03-22,fraud,-2,2,-4,6,banking,2021-01-01
156,471,WRB,NYK,2021-04-12,fraud,-2,2,-4,6,insurance,2021-04-01
157,473,WRB,NYK,2021-04-13,fraud,-2,2,-4,6,insurance,2021-04-01
158,477,WRB,NYK,2019-02-04,fraud,-2,2,-4,6,insurance,2019-01-01
159,481,ZION,NYK,2021-04-14,fraud,-2,2,-4,6,banking,2021-04-01
160,482,ZION,NYK,2021-04-14,fraud,-2,2,-4,6,banking,2021-04-01
161,484,ZION,NYK,2021-04-12,fraud,-2,2,-4,6,banking,2021-04-01
162,486,ZION,NYK,2021-04-14,fraud,-2,2,-4,6,banking,2021-04-01
163,487,ZION,NYK,2021-04-13,fraud,-2,2,-4,6,banking,2021-04-01

## грузим

In [14]:
ticker = {i: pd.read_excel("tickers/_Results/panel-debt-equity-ratio.xlsx", sheet_name=i) for i in range(7)}

In [25]:
ticker[0].head()#.query("date >= '2010-05-01'")

  company       date  total debt  equity  DERatio
0     AEL 2005-03-31       11.35    0.32    35.76
1     AEL 2005-06-30       12.07    0.35    34.74
2     AEL 2005-09-30       12.89    0.35    37.01
3     AEL 2005-12-31       13.52    0.52    26.04
4     AEL 2006-03-31       14.17    0.49    28.96

## фильтруем
* компании в алфавитном
* везде дата > 01.05.10

In [85]:
ticker1 = {i: df.sort_values("company").query("date >= '2010-05-01'") for i, df in ticker.items()}

In [87]:
df0 = ticker1[0].set_index(["company", "date"])
for i in range(1, 7):
    df0 = df0.join(ticker1[i].set_index(["company", "date"]), how="inner")
ticker2 = df0.reset_index().assign(quarter=lambda df: df.date.apply(lambda d: pd.datetime(d.year, (d.month-1) // 3 * 3 + 1, 1)))

In [137]:
import re
def fmtB(s):
    if pd.isna(s): return
    s = s.replace(",", "")
    m = re.match(r"^\$(.+)B$", s).group(1)
    return float(m)

In [107]:
ticker2m1 = ticker2.assign(quarter=lambda df: df.quarter + pd.tseries.offsets.DateOffset(months=3))

In [138]:
request_ticker = (
    request1.set_index(["company", "quarter"])
    .join(ticker2.set_index(["company", "quarter"]), rsuffix="_ticker")
    .assign(NI=lambda df: df.NI.apply(fmtB), Asset=lambda df: df.Asset.apply(fmtB))
)
request_tickerm1 = (
    request1.set_index(["company", "quarter"])
    .join(ticker2m1.set_index(["company", "quarter"]), rsuffix="_ticker")
    .assign(NI=lambda df: df.NI.apply(fmtB), Asset=lambda df: df.Asset.apply(fmtB))
)

In [145]:
request_ticker.columns

Index(['event', 'market', 'date', 'type', 'l', 'r', 'w', 'c', 'sector',
       'date_ticker', 'total debt', 'equity', 'DERatio', 'ebitda', 'ebit',
       'eps', 'NI', 'Asset', 'ROA', 'MV', 'BV', 'PB', 'shares'],
      dtype='object')

In [151]:
diff_columns = ['total debt', 'equity', 'DERatio', 'ebitda', 'ebit',
       'eps', 'NI', 'Asset', 'ROA', 'MV', 'BV', 'PB', 'shares']
diff_out_columns = [s + "_diff" for s in diff_columns]

In [152]:
request_ticker[diff_out_columns] = request_ticker[diff_columns] - request_tickerm1[diff_columns]

In [154]:
request_ticker.reset_index().to_csv("request_ticker_diffs.csv")